version: "3.9"
services:

  server:
    image: docker.moyonero.com/tfg-aps:dev-david-resumenes
    container_name: aps-web
    restart: always
    environment:
      - MYSQL_IP=192.168.1.190
      - MYSQL_PORT=33061
      - MYSQL_USER=aps
      - MYSQL_PASSWORD=aps
      - MYSQL_DATABASE=aps
      - JWT_SECRET=aps
      - PORT=8080
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aps-web.entrypoints=web"
      - "traefik.http.routers.aps-web.rule=Host(`aps.moyonero.com`)"
      - "traefik.http.routers.aps-web.middlewares=redirect"
      - "traefik.http.routers.aps-web-secure.entrypoints=websecure"
      - "traefik.http.routers.aps-web-secure.rule=Host(`aps.moyonero.com`)"
      - "traefik.http.routers.aps-web-secure.tls=true"
      - "traefik.http.routers.aps-web-secure.tls.certresolver=moyonero.com"
      - "traefik.http.services.aps-web-secure.loadbalancer.server.port=8080"

networks:
  reverse-proxy_default:
    external: true