version: "3.9"
services:
  db:
    image: mariadb
    container_name: aps-mariadb
    restart: always
    ports:
      - 33061:3306
    environment:
      MARIADB_USER: aps
      MARIADB_PASSWORD: aps
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aps
    volumes:
      - /volume1/docker/tfg-aps/database/scripts:/docker-entrypoint-initdb.d
      - /volume1/docker/tfg-aps/database/mysql:/var/lib/mysql
      - /volume1/docker/tfg-aps/database/config:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin
    container_name: aps-phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`aps-db.moyonero.com`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.routers.phpmyadmin.service=aps-phpmyadmin"

  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: aps-jenkins
    restart: always
    environment:
      - COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
    volumes:
      - /volume1/docker/tfg-aps/jenkins:/var/jenkins_home
      - /volume1/docker/tfg-aps/jenkins/downloads:/var/jenkins_home/downloads
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`aps-jenkins.moyonero.com`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.routers.jenkins.service=aps-jenkins"

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: aps-heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /volume1/docker/tfg-aps/heimdall/config:/config
    ports:
      - 1004:80
      - 1005:443
    restart: unless-stopped
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`aps-dashboard.moyonero.com`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
      - "traefik.http.routers.heimdall.service=aps-heimdall"

  sonarqube:
    image: sonarqube:latest
    container_name: aps-sonarqube
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/tfg-aps/sonar/data:/opt/sonarqube/data
      - /volume1/docker/tfg-aps/sonar/logs:/opt/sonarqube/logs
      - /volume1/docker/tfg-aps/sonar/extensions:/opt/sonarqube/extensions
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.http.services.sonar.loadbalancer.server.port=9000"
      - "traefik.enable=true"
      - "traefik.http.routers.sonar.rule=Host(`aps-sonar.moyonero.com`)"
      - "traefik.http.routers.sonar.entrypoints=web"
      - "traefik.http.routers.sonar.service=aps-sonar"

networks:
  reverse-proxy_default:
    external: true