version: "3.9"
services:
  db:
    image: mariadb
    container_name: aps-mariadb
    restart: always
    ports:
      - 33061:3306
    environment:
      MARIADB_USER: aps
      MARIADB_PASSWORD: aps
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aps
    volumes:
      - /volume1/docker/tfg-aps/database/scripts:/docker-entrypoint-initdb.d
      - /volume1/docker/tfg-aps/database/mysql:/var/lib/mysql
      - /volume1/docker/tfg-aps/database/config:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin
    container_name: aps-phpmyadmin
    restart: always
    ports:
      - 1002:80
    environment:
      - PMA_ARBITRARY=1

  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: aps-jenkins
    restart: always
    ports:
      - 1003:8080
      - 50001:50000
    environment:
      - COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
    volumes:
      - /volume1/docker/tfg-aps/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: aps-heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /volume1/docker/tfg-aps/heimdall/config:/config
    ports:
      - 1004:80
      - 1005:443
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: aps-sonarqube
    restart: always
    ports:
      - 1006:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/tfg-aps/sonar/data:/opt/sonarqube/data
      - /volume1/docker/tfg-aps/sonar/logs:/opt/sonarqube/logs
      - /volume1/docker/tfg-aps/sonar/extensions:/opt/sonarqube/extensions
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
