version: "3.9"
services:
  db:
    image: mariadb
    container_name: aps-mariadb
    restart: always
    ports:
      - 33061:3306
    environment:
      MARIADB_USER: aps
      MARIADB_PASSWORD: aps
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    container_name: aps-phpmyadmin
    restart: always
    ports:
      - 1002:80
    environment:
      - PMA_ARBITRARY=1

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: aps-jenkins
    restart: always
    ports:
      - 1003:8080
      - 50001:50000
    environment:
      - COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
    volumes:
      - /volume1/docker/tfg-aps/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: aps-heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /volume1/docker/tfg-aps/heimdall/config:/config
    ports:
      - 1004:80
      - 1005:443
    restart: unless-stopped
