version: "3.9"
services:
  db:
    image: mariadb
    container_name: aps-mariadb
    restart: always
    ports:
      - 33061:3306
    environment:
      MARIADB_USER: aps
      MARIADB_PASSWORD: aps
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aps
    volumes:
      - /volume1/docker/tfg-aps/database/scripts:/docker-entrypoint-initdb.d
      - /volume1/docker/tfg-aps/database/mysql:/var/lib/mysql
      - /volume1/docker/tfg-aps/database/config:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin
    container_name: aps-phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aps-phpmyadmin.entrypoints=web"
      - "traefik.http.routers.aps-phpmyadmin.rule=Host(`aps-phpmyadmin.moyonero.com`)"
      - "traefik.http.routers.aps-phpmyadmin.middlewares=redirect"
      - "traefik.http.routers.aps-phpmyadmin-secure.entrypoints=websecure"
      - "traefik.http.routers.aps-phpmyadmin-secure.rule=Host(`aps-phpmyadmin.moyonero.com`)"
      - "traefik.http.routers.aps-phpmyadmin-secure.tls=true"
      - "traefik.http.routers.aps-phpmyadmin-secure.tls.certresolver=moyonero.com"
      - "traefik.http.services.aps-phpmyadmin-secure.loadbalancer.server.port=80"

  jenkins:
    image: jenkinsci/blueocean:latest
    container_name: aps-jenkins
    restart: always
    environment:
      - COPY_REFERENCE_FILE_LOG=/var/jenkins_home/copy_reference_file.log
    volumes:
      - /volume1/docker/tfg-aps/jenkins:/var/jenkins_home
      - /volume1/docker/tfg-aps/jenkins/downloads:/var/jenkins_home/downloads
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aps-jenkins.entrypoints=web"
      - "traefik.http.routers.aps-jenkins.rule=Host(`aps-jenkins.moyonero.com`)"
      - "traefik.http.routers.aps-jenkins.middlewares=redirect"
      - "traefik.http.routers.aps-jenkins-secure.entrypoints=websecure"
      - "traefik.http.routers.aps-jenkins-secure.rule=Host(`aps-jenkins.moyonero.com`)"
      - "traefik.http.routers.aps-jenkins-secure.tls=true"
      - "traefik.http.routers.aps-jenkins-secure.tls.certresolver=moyonero.com"
      - "traefik.http.services.aps-jenkins-secure.loadbalancer.server.port=8080"

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: aps-heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /volume1/docker/tfg-aps/heimdall/config:/config
    restart: unless-stopped
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aps-heimdall.entrypoints=web"
      - "traefik.http.routers.aps-heimdall.rule=Host(`aps-dashboard.moyonero.com`)"
      - "traefik.http.routers.aps-heimdall.middlewares=redirect"
      - "traefik.http.routers.aps-heimdall-secure.entrypoints=websecure"
      - "traefik.http.routers.aps-heimdall-secure.rule=Host(`aps-dashboard.moyonero.com`)"
      - "traefik.http.routers.aps-heimdall-secure.tls=true"
      - "traefik.http.routers.aps-heimdall-secure.tls.certresolver=moyonero.com"
      - "traefik.http.services.aps-heimdall-secure.loadbalancer.server.port=80"

  sonarqube:
    image: sonarqube:latest
    container_name: aps-sonarqube
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/tfg-aps/sonar/data:/opt/sonarqube/data
      - /volume1/docker/tfg-aps/sonar/logs:/opt/sonarqube/logs
      - /volume1/docker/tfg-aps/sonar/extensions:/opt/sonarqube/extensions
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    networks:
      - reverse-proxy_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aps-sonar.entrypoints=web"
      - "traefik.http.routers.aps-sonar.rule=Host(`aps-sonar.moyonero.com`)"
      - "traefik.http.routers.aps-sonar.middlewares=redirect"
      - "traefik.http.routers.aps-sonar-secure.entrypoints=websecure"
      - "traefik.http.routers.aps-sonar-secure.rule=Host(`aps-sonar.moyonero.com`)"
      - "traefik.http.routers.aps-sonar-secure.tls=true"
      - "traefik.http.routers.aps-sonar-secure.tls.certresolver=moyonero.com"
      - "traefik.http.services.aps-sonar-secure.loadbalancer.server.port=9000"

networks:
  reverse-proxy_default:
    external: true